POST http://localhost:3333/videos
Content-type: application/json

{
    "title": "Memeso tomando no cu e rindo",
    "description": "Esse é o primeiro video do memeso",
    "duration": 160
}

###

GET http://localhost:3333/videos

###

PUT http://localhost:3333/videos/74eb557d-b6c6-4790-a0cb-a972e61c163f
Content-type: application/json

{
    "title": "Video 3",
    "description": "Esse é o terceiro video",
    "duration": 120
}

###
DELETE http://localhost:3333/videos/74eb557d-b6c6-4790-a0cb-a972e61c163f